on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

#    - name: Run Migrations
#      run: docker-compose exec app python manage.py migrate
#
#    - name: Run Tests
#      run: docker-compose exec app python manage.py test
    - name: Install Ruff
      run: docker-compose exec app pip install ruff

    - name: Run Ruff Check
      run: docker-compose exec app ruff check .

    - name: Run Ruff Check with Fixes
      run: docker-compose exec app ruff check --fix .

    - name: Run Ruff Format
      run: docker-compose exec app ruff format .
